import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  '@global': {
    '*': {
      margin: 0,
      padding: 0,
      boxSizing: 'border-box',
      fontFamily: 'Arial, sans-serif',
    },
  },
  notFoundContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '40px',
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
  },
  backButton: {
    marginTop: '20px',
    padding: '10px 20px',
    backgroundColor: '#333',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: '#555',
    },
  },
  mainContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '40px 20px',
    backgroundColor: '#f0f0f5',
    fontFamily: 'Arial, sans-serif',
    minHeight: '100vh',
  },
  photoCard: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    cursor: 'pointer',
    '&:hover': {
      transform: 'scale(1.03)',
      boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    },
  },
  image: {
    width: '100%',
    height: '200px',
    objectFit: 'cover',
    borderRadius: '8px',
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'scale(1.05)',
    },
  },
  photographerText: {
    marginTop: '8px',
    color: '#666',
    fontSize: '14px',
    textAlign: 'center',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '20px',
  },
  searchInput: {
    width: '100%',
    maxWidth: '400px',
    padding: '12px 15px',
    fontSize: '16px',
    borderRadius: '8px',
    border: '1px solid #ccc',
    outline: 'none',
    transition: 'border-color 0.3s ease',
    '&:focus': {
      borderColor: '#555',
    },
    marginBottom: '10px',
  },
  searchButton: {
    padding: '12px 20px',
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#fff',
    backgroundColor: '#333',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: '#555',
    },
    marginBottom: '20px',
  },
  errorMessage: {
    color: 'red',
    fontSize: '14px',
    marginBottom: '10px',
  },
  photoMeta: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '16px',
    width: '100%',
    maxWidth: '1200px',
    margin: '30px auto',
  },
  card: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      transform: 'scale(1.05)',
      boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    },
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      borderRadius: '8px',
    },
  },
  overlay: {
    position: 'absolute',
    bottom: '0',
    left: '0',
    width: '100%',
    padding: '10px',
    color: '#fff',
    background: 'rgba(0, 0, 0, 0.5)',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  modalContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '20px',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    animation: '$fadeIn 0.5s ease-in-out',
    maxWidth: '90%',
    width: '600px',
    margin: '20px auto',
  },
  modalImage: {
    width: '100%',
    borderRadius: '10px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    transition: 'transform 0.6s ease',
    '&:hover': {
      transform: 'scale(1.05)',
    },
  },
  modalText: {
    textAlign: 'center',
    fontSize: '18px',
    color: '#333',
    marginTop: '10px',
    fontWeight: 'bold',
  },
  photographer: {
    fontSize: '16px',
    marginTop: '4px',
    fontStyle: 'italic',
    color: '#555',
  },
  description: {
    marginTop: '10px',
    fontSize: '14px',
    color: '#666',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  favoriteIcon: {
    color: 'grey',
    cursor: 'pointer',
    margin: '10px',
  },
  favoriteIconActive: {
    color: 'red',
    cursor: 'pointer',
    margin: '10px',
  },
  '@keyframes fadeIn': {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  backIcon: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    fontSize: '18px',
    color: '#333',
    cursor: 'pointer',
    padding: '10px',
    background: '#f0f0f0',
    borderRadius: '50%',
    transition: 'background 0.3s, transform 0.2s',
    '&:hover': {
      background: '#ddd',
      transform: 'scale(1.1)',
    },
  },

  favoritesContainer: {
    padding: '2rem',
    textAlign: 'center',
  },
  emptyMessage: {
    fontSize: '1.5rem',
    color: '#888',
    marginTop: '2rem',
  },
  favoritesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
    marginTop: '2rem',
  },
  favoriteItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f4f4f4',
    padding: '1rem',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.2s ease-in-out',
    '&:hover': {
      transform: 'scale(1.05)',
    },
  },
  favoritesImage: {
    width: '100%',
    height: '200px',
    borderRadius: '8px',
    marginBottom: '0.5rem',
    objectFit: 'cover',
  },
  favoritesPhotographer: {
    fontSize: '1rem',
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2rem',
    backgroundColor: '#333',
    color: '#fff',
    width: '1200px',
    borderRadius: '15px',
  },
  headerTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  nav: {
    display: 'flex',
    gap: '1rem',
  },
  navLink: {
    color: '#fff',
    textDecoration: 'none',
    fontSize: '1.1rem',
    '&:hover': {
      color: '#ddd',
    },
  },
  removeButton: {
    backgroundColor: '#ff5c5c',
    color: '#fff',
    border: 'none',
    borderRadius: '5px',
    padding: '8px 12px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '0.9rem',
    transition: 'background-color 0.3s ease',
    marginTop: '10px',
    '&:hover': {
      backgroundColor: '#ff3333',
    },
  },
  icon: {
    fontSize: '1.2rem',
  },
  filterContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '20px',
  },
  dropdown: {
    position: 'relative',
    display: 'inline-block',
  },
  dropdownButton: {
    backgroundColor: '#4CAF50',
    color: 'white',
    padding: '10px 20px',
    fontSize: '16px',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '4px',
    '&:hover': {
      backgroundColor: '#45a049',
    },
  },
  dropdownContent: {
    display: 'none',
    position: 'absolute',
    backgroundColor: '#f9f9f9',
    minWidth: '160px',
    boxShadow: '0px 8px 16px rgba(0, 0, 0, 0.2)',
    zIndex: '1',
    borderRadius: '4px',
    '& a': {
      color: 'black',
      padding: '12px 16px',
      textDecoration: 'none',
      display: 'block',
      '&:hover': {
        backgroundColor: '#ddd',
      },
    },
  },
  dropdownButtonHover: {
    '&:hover + $dropdownContent': {
      display: 'block',
    },
  },
  dropdownSelect: {
    padding: '10px 20px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    cursor: 'pointer',
    '&:hover': {
      borderColor: '#888',
    },
    '&:focus': {
      outline: 'none',
      borderColor: '#4CAF50',
    },
  },
  downloadButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    padding: '0.5rem 1rem',
    cursor: 'pointer',
    marginTop: '10px',
    '&:hover': {
      backgroundColor: '#45a049',
    },
  },
  shareButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#1DA1F2',
    color: 'white',
    border: 'none',
    padding: '0.5rem 1rem',
    cursor: 'pointer',
    marginTop: '10px',
    '&:hover': {
      backgroundColor: '#0d95e8',
    },
  },
  shareNotification: {
    position: 'fixed',
    top: 20,
    right: 20,
    padding: '10px 20px',
    backgroundColor: '#4caf50',
    color: 'white',
    borderRadius: 5,
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.3)',
    animation: '$fadeInOut 3s ease forwards',
  },
  '@keyframes fadeInOut': {
    '0%': { opacity: 0 },
    '10%': { opacity: 1 },
    '90%': { opacity: 1 },
    '100%': { opacity: 0 },
  },
});
